name: Dependabot auto-merge minor/patch
on: pull_request

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  dependabot:
    uses: ShaneMcC/.github/.github/workflows/automergeMinorOrPatch.yml@master
    secrets: inherit
